services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: always
    volumes:
      - ${OLLAMA_DATA_FOLDER:-./ollama_data}:/root/.ollama
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - video
      - "988"
    # Instalar o pacote 'nvidia-cg-toolkit' no host e descomentar:
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    networks:
      external:
        ipv4_address: ${OLLAMA_IP}

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: always
    volumes:
      - ${OPEN_WEBUI_DATA_FOLDER:-./open-webui_data}:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://${OLLAMA_IP}:11434
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
    depends_on:
      - ollama
    networks:
      external:
        ipv4_address: ${OPEN_WEBUI_IP}

networks:
  external:
    external: true
    name: ${EXTERNAL_NETWORK_NAME}